/* MEDIDAS */

CURSOS DE FORMACIÓN CONTINUA (DESDE 1 DÍA HASTA 2 MESES) - SEP = 
SUM(SEPTIEMBRE[CURSOS DE FORMACIÓN CONTINUA (DESDE 1 DÍA HASTA 2 MESES) (S1)]) +
SUM(SEPTIEMBRE[CURSOS DE FORMACIÓN CONTINUA (DESDE 1 DÍA HASTA 2 MESES) (S2)]) +
SUM(SEPTIEMBRE[CURSOS DE FORMACIÓN CONTINUA (DESDE 1 DÍA HASTA 2 MESES) (S3)]) +
SUM(SEPTIEMBRE[CURSOS DE FORMACIÓN CONTINUA (DESDE 1 DÍA HASTA 2 MESES) (S4)])

CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CONTADO - SEP = 
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CONTADO (S1)]) +
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CONTADO (S2)]) +
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CONTADO (S3)]) +
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CONTADO (S4)])

CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CREDITO - SEP = 
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CREDITO (S1)]) +
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CREDITO (S2)]) +
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CREDITO (S3)]) +
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CREDITO (S4)])

PREUNIVERSITARIOS / SI ESAM CONTADO - SEP = 
SUM(SEPTIEMBRE[PREUNIVERSITARIOS // SI ESAM: PAQUETES MENSUAL CONTADO (S1)]) +
SUM(SEPTIEMBRE[PREUNIVERSITARIOS // SI ESAM: PAQUETES MENSUAL CONTADO (S2)]) +
SUM(SEPTIEMBRE[PREUNIVERSITARIOS // SI ESAM: PAQUETES MENSUAL CONTADO (S3)]) +
SUM(SEPTIEMBRE[PREUNIVERSITARIOS // SI ESAM: PAQUETES MENSUAL CONTADO (S4)])

PREUNIVERSITARIOS / SI ESAM CREDITO - SEP = 
SUM(SEPTIEMBRE[PREUNIVERSITARIOS // SI ESAM: PAQUETES MENSUAL CREDITO (S1)]) +
SUM(SEPTIEMBRE[PREUNIVERSITARIOS // SI ESAM: PAQUETES MENSUAL CREDITO (S2)]) +
SUM(SEPTIEMBRE[PREUNIVERSITARIOS // SI ESAM: PAQUETES MENSUAL CREDITO (S3)]) +
SUM(SEPTIEMBRE[PREUNIVERSITARIOS // SI ESAM: PAQUETES MENSUAL CREDITO (S4)])

DIPLOMADOS TECNICOS ISPI DE 4 MESES ANTICIPO - SEP = 
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES ANTICIPO (S1)]) +
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES ANTICIPO (S2)]) +
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES ANTICIPO (S3)]) +
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES ANTICIPO (S4)])

DIPLOMADOS TECNICOS ISPI DE 4 MESES CONTADO - SEP = 
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES CONTADO (S1)]) +
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES CONTADO (S2)]) +
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES CONTADO (S3)]) +
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES CONTADO (S4)])

DIPLOMADOS TECNICOS ISPI DE 4 MESES CREDITO - SEP = 
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES CREDITO (S1)]) +
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES CREDITO (S2)]) +
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES CREDITO (S3)]) +
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES CREDITO (S4)])

DIPLOMADOS TECNICOS UPI DE 4 MESES / FORMACION CONTINUA UPI ANTICIPO - SEP = 
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) ANTICIPO (S1)]) +
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) ANTICIPO (S2)]) +
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) ANTICIPO (S1)]) +
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) ANTICIPO (S1)])

DIPLOMADOS TECNICOS UPI DE 4 MESES / FORMACION CONTINUA UPI CONTADO - SEP = 
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) CONTADO (S1)]) +
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) CONTADO (S2)]) +
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) CONTADO (S3)]) +
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) CONTADO (S4)])

DIPLOMADOS TECNICOS UPI DE 4 MESES / FORMACION CONTINUA UPI CREDITO - SEP = 
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) CREDITO (S1)]) +
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) CREDITO (S2)]) +
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) CREDITO (S3)]) +
SUM(SEPTIEMBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) CREDITO (S4)])

CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) / NIDITO ANTICIPO - SEP = 
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI ANTICIPO (S1)]) +
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI ANTICIPO (S2)]) +
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI ANTICIPO (S3)]) +
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI ANTICIPO (S4)])

CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) / NIDITO CONTADO - SEP = 
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI CONTADO (S1)]) +
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI CONTADO (S2)]) +
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI CONTADO (S3)]) +
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI CONTADO (S4)])

CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) / NIDITO CREDITO - SEP = 
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI CREDITO (S1)]) +
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI CREDITO (S2)]) +
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI CREDITO (S3)]) +
SUM(SEPTIEMBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI CREDITO (S4)])

CARRERAS - LICENCIATURAS / KINDER 1RA - 2DA SECCION / ALUMNOS PRIMARIA - SECUNDARIA / DIPLOMADOS UPI ANTICIPO - SEP = 
SUM(SEPTIEMBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) ANTICIPO (S1)]) +
SUM(SEPTIEMBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) ANTICIPO (S2)]) +
SUM(SEPTIEMBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) ANTICIPO (S3)]) +
SUM(SEPTIEMBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) ANTICIPO (S4)])

CARRERAS - LICENCIATURAS / KINDER 1RA - 2DA SECCION / ALUMNOS PRIMARIA - SECUNDARIA / DIPLOMADOS UPI CONTADO - SEP = 
SUM(SEPTIEMBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) CONTADO (S1)]) +
SUM(SEPTIEMBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) CONTADO (S2)]) +
SUM(SEPTIEMBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) CONTADO (S3)]) +
SUM(SEPTIEMBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) CONTADO (S4)])

CARRERAS - LICENCIATURAS / KINDER 1RA - 2DA SECCION / ALUMNOS PRIMARIA - SECUNDARIA / DIPLOMADOS UPI CREDITO - SEP = 
SUM(SEPTIEMBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) CREDITO (S1)]) +
SUM(SEPTIEMBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) CREDITO (S2)]) +
SUM(SEPTIEMBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) CREDITO (S3)]) +
SUM(SEPTIEMBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) CREDITO (S4)])

PREINICIAL / ESPECIALIDADES POSGRADO ANTICIPO - SEP = 
SUM(SEPTIEMBRE[PREINICIAL // ESPECIALIDADES ANTICIPO (S1)]) +
SUM(SEPTIEMBRE[PREINICIAL // ESPECIALIDADES ANTICIPO (S2)]) +
SUM(SEPTIEMBRE[PREINICIAL // ESPECIALIDADES ANTICIPO (S3)]) +
SUM(SEPTIEMBRE[PREINICIAL // ESPECIALIDADES ANTICIPO (S4)])

PREINICIAL / ESPECIALIDADES POSGRADO CONTADO - SEP = 
SUM(SEPTIEMBRE[PREINICIAL // ESPECIALIDADES CONTADO (S1)]) +
SUM(SEPTIEMBRE[PREINICIAL // ESPECIALIDADES CONTADO (S2)]) +
SUM(SEPTIEMBRE[PREINICIAL // ESPECIALIDADES CONTADO (S3)]) +
SUM(SEPTIEMBRE[PREINICIAL // ESPECIALIDADES CONTADO (S4)])

PREINICIAL / ESPECIALIDADES POSGRADO CREDITO - SEP = 
SUM(SEPTIEMBRE[PREINICIAL // ESPECIALIDADES CREDITO (S1)]) +
SUM(SEPTIEMBRE[PREINICIAL // ESPECIALIDADES CREDITO (S2)]) +
SUM(SEPTIEMBRE[PREINICIAL // ESPECIALIDADES CREDITO (S3)]) +
SUM(SEPTIEMBRE[PREINICIAL // ESPECIALIDADES CREDITO (S4)])

DIPLOMADOS POSGRADO ANTICIPO - SEP = 
SUM(SEPTIEMBRE[DIPLOMADOS ANTICIPO (S1)]) +
SUM(SEPTIEMBRE[DIPLOMADOS ANTICIPO (S2)]) +
SUM(SEPTIEMBRE[DIPLOMADOS ANTICIPO (S3)]) +
SUM(SEPTIEMBRE[DIPLOMADOS ANTICIPO (S4)])

DIPLOMADOS POSGRADO CONTADO - SEP = 
SUM(SEPTIEMBRE[DIPLOMADOS CONTADO (S1)]) +
SUM(SEPTIEMBRE[DIPLOMADOS CONTADO (S2)]) +
SUM(SEPTIEMBRE[DIPLOMADOS CONTADO (S3)]) +
SUM(SEPTIEMBRE[DIPLOMADOS CONTADO (S4)])

DIPLOMADOS POSGRADO CREDITO - SEP = 
SUM(SEPTIEMBRE[DIPLOMADOS CREDITO (S1)]) +
SUM(SEPTIEMBRE[DIPLOMADOS CREDITO (S2)]) +
SUM(SEPTIEMBRE[DIPLOMADOS CREDITO (S3)]) +
SUM(SEPTIEMBRE[DIPLOMADOS CREDITO (S4)])

DIPLOMADOS POSGRADO UABJB CONTADO - SEP = 
SUM(SEPTIEMBRE[DIPLOMADOS CONTADO UABJB (S1)]) +
SUM(SEPTIEMBRE[DIPLOMADOS CONTADO UABJB (S2)]) +
SUM(SEPTIEMBRE[DIPLOMADOS CONTADO UABJB (S3)]) +
SUM(SEPTIEMBRE[DIPLOMADOS CONTADO UABJB (S4)])

DIPLOMADOS POSGRADO UABJB CREDITO - SEP = 
SUM(SEPTIEMBRE[DIPLOMADOS CREDITO UABJB (S1)]) +
SUM(SEPTIEMBRE[DIPLOMADOS CREDITO UABJB (S2)]) +
SUM(SEPTIEMBRE[DIPLOMADOS CREDITO UABJB (S3)]) +
SUM(SEPTIEMBRE[DIPLOMADOS CREDITO UABJB (S4)])

MAESTRIAS POSGRADO ANTICIPO - SEP = 
SUM(SEPTIEMBRE[MAESTRIAS ANTICIPO (S1)]) +
SUM(SEPTIEMBRE[MAESTRIAS ANTICIPO (S2)]) +
SUM(SEPTIEMBRE[MAESTRIAS ANTICIPO (S3)]) +
SUM(SEPTIEMBRE[MAESTRIAS ANTICIPO (S4)])

MAESTRIAS POSGRADO CONTADO - SEP = 
SUM(SEPTIEMBRE[MAESTRIAS CONTADO (S1)]) +
SUM(SEPTIEMBRE[MAESTRIAS CONTADO (S2)]) +
SUM(SEPTIEMBRE[MAESTRIAS CONTADO (S3)]) +
SUM(SEPTIEMBRE[MAESTRIAS CONTADO (S4)])

MAESTRIAS POSGRADO CREDITO - SEP = 
SUM(SEPTIEMBRE[MAESTRIAS CREDITO (S1)]) +
SUM(SEPTIEMBRE[MAESTRIAS CREDITO (S2)]) +
SUM(SEPTIEMBRE[MAESTRIAS CREDITO (S3)]) +
SUM(SEPTIEMBRE[MAESTRIAS CREDITO (S4)])

MAESTRIAS POSGRADO UABJB CONTADO - SEP = 
SUM(SEPTIEMBRE[MAESTRIAS CONTADO UABJB (S1)]) +
SUM(SEPTIEMBRE[MAESTRIAS CONTADO UABJB (S2)]) +
SUM(SEPTIEMBRE[MAESTRIAS CONTADO UABJB (S3)]) +
SUM(SEPTIEMBRE[MAESTRIAS CONTADO UABJB (S4)])

MAESTRIAS POSGRADO UABJB CREDITO - SEP = 
SUM(SEPTIEMBRE[MAESTRIAS CREDITO UABJB (S1)]) +
SUM(SEPTIEMBRE[MAESTRIAS CREDITO UABJB (S2)]) +
SUM(SEPTIEMBRE[MAESTRIAS CREDITO UABJB (S3)]) +
SUM(SEPTIEMBRE[MAESTRIAS CREDITO UABJB (S4)])

/* TOTALES */

TOTAL CAPACITACIÓN CA - SEP = 
[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CONTADO - SEP] +
[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CREDITO - SEP]

TOTAL CAPACITACIÓN LA / NIDITO / CARRERAS UPI - SEP = 
[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) / NIDITO CONTADO - SEP] +
[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) / NIDITO CREDITO - SEP]

TOTAL CARRERAS / KINDER / ALUMNOS / UPI PG - SEP = 
[CARRERAS - LICENCIATURAS / KINDER 1RA - 2DA SECCION / ALUMNOS PRIMARIA - SECUNDARIA / DIPLOMADOS UPI CONTADO - SEP] +
[CARRERAS - LICENCIATURAS / KINDER 1RA - 2DA SECCION / ALUMNOS PRIMARIA - SECUNDARIA / DIPLOMADOS UPI CREDITO - SEP]

TOTAL ESPECIALIDADES POSGRADO - SEP = 
[PREINICIAL / ESPECIALIDADES POSGRADO ANTICIPO - SEP] + 
[PREINICIAL / ESPECIALIDADES POSGRADO CREDITO - SEP]

TOTAL DIPLOMADOS POSGRADO - SEP = 
[DIPLOMADOS POSGRADO CONTADO - SEP] + 
[DIPLOMADOS POSGRADO CREDITO - SEP] +
[DIPLOMADOS POSGRADO UABJB CONTADO - SEP] +
[DIPLOMADOS POSGRADO UABJB CREDITO - SEP]

TOTAL UPI FC - SEP = 
[DIPLOMADOS TECNICOS UPI DE 4 MESES / FORMACION CONTINUA UPI CONTADO - SEP] +
[DIPLOMADOS TECNICOS UPI DE 4 MESES / FORMACION CONTINUA UPI CREDITO - SEP]

TOTAL DIPLOMADOS - SEP = 
[TOTAL DIPLOMADOS POSGRADO - SEP] + 
[TOTAL CARRERAS / KINDER / ALUMNOS / UPI PG - SEP] +
[TOTAL UPI FC - SEP]

TOTAL MAESTRIAS POSGRADO - SEP = 
[MAESTRIAS POSGRADO CONTADO - SEP] + 
[MAESTRIAS POSGRADO CREDITO - SEP] +
[MAESTRIAS POSGRADO UABJB CONTADO - SEP] +
[MAESTRIAS POSGRADO UABJB CREDITO - SEP]

TOTAL POSGRADO - SEP = 
[TOTAL DIPLOMADOS POSGRADO - SEP] + 
[TOTAL ESPECIALIDADES POSGRADO - SEP] + 
[TOTAL MAESTRIAS POSGRADO - SEP]

TOTAL POSGRADO Y UPI FC - SEP = 
[TOTAL POSGRADO - SEP] +
[TOTAL UPI FC - SEP]

TOTAL CORTO ALCANCE - SEP = 
[CURSOS DE FORMACIÓN CONTINUA (DESDE 1 DÍA HASTA 2 MESES) - SEP] +
[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CONTADO - SEP] +
[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CREDITO - SEP] +
[PREUNIVERSITARIOS / SI ESAM CONTADO - SEP] +
[PREUNIVERSITARIOS / SI ESAM CREDITO - SEP] +
[DIPLOMADOS TECNICOS ISPI DE 4 MESES CONTADO - SEP] +
[DIPLOMADOS TECNICOS ISPI DE 4 MESES CREDITO - SEP] +
[DIPLOMADOS TECNICOS UPI DE 4 MESES / FORMACION CONTINUA UPI CONTADO - SEP]+
[DIPLOMADOS TECNICOS UPI DE 4 MESES / FORMACION CONTINUA UPI CREDITO - SEP]

TOTAL LARGO ALCANCE - SEP = 
SUM(SEPTIEMBRE[SUBTOTAL LARGO ALCANCE COMPLETO (S1)]) +
SUM(SEPTIEMBRE[SUBTOTAL LARGO ALCANCE COMPLETO (S2)]) +
SUM(SEPTIEMBRE[SUBTOTAL LARGO ALCANCE COMPLETO (S3)]) +
SUM(SEPTIEMBRE[SUBTOTAL LARGO ALCANCE COMPLETO (S4)])

TOTAL LARGO ALCANCE CONTADO - SEP = 
SUM(SEPTIEMBRE[SUBTOTAL LARGO ALCANCE - PLAN AL CONTADO COMPLETO (S1)]) +
SUM(SEPTIEMBRE[SUBTOTAL LARGO ALCANCE - PLAN AL CONTADO COMPLETO (S2)]) +
SUM(SEPTIEMBRE[SUBTOTAL LARGO ALCANCE - PLAN AL CONTADO COMPLETO (S3)]) +
SUM(SEPTIEMBRE[SUBTOTAL LARGO ALCANCE - PLAN AL CONTADO COMPLETO (S4)])

TOTAL SEDE - SEP = 
SUM(SEPTIEMBRE[TOTAL DE SEDE (S1)]) +
SUM(SEPTIEMBRE[TOTAL DE SEDE (S2)]) +
SUM(SEPTIEMBRE[TOTAL DE SEDE (S3)]) +
SUM(SEPTIEMBRE[TOTAL DE SEDE (S4)])