/* MEDIDAS */

CURSOS DE FORMACIÓN CONTINUA (DESDE 1 DÍA HASTA 2 MESES) - OCT = 
SUM(OCTUBRE[CURSOS DE FORMACIÓN CONTINUA (DESDE 1 DÍA HASTA 2 MESES) (S1)]) +
SUM(OCTUBRE[CURSOS DE FORMACIÓN CONTINUA (DESDE 1 DÍA HASTA 2 MESES) (S2)]) +
SUM(OCTUBRE[CURSOS DE FORMACIÓN CONTINUA (DESDE 1 DÍA HASTA 2 MESES) (S3)]) +
SUM(OCTUBRE[CURSOS DE FORMACIÓN CONTINUA (DESDE 1 DÍA HASTA 2 MESES) (S4)])

CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CONTADO - OCT = 
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CONTADO (S1)]) +
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CONTADO (S2)]) +
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CONTADO (S3)]) +
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CONTADO (S4)])

CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CREDITO - OCT = 
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CREDITO (S1)]) +
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CREDITO (S2)]) +
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CREDITO (S3)]) +
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CREDITO (S4)])

PREUNIVERSITARIOS / SI ESAM CONTADO - OCT = 
SUM(OCTUBRE[PREUNIVERSITARIOS // SI ESAM: PAQUETES MENSUAL CONTADO (S1)]) +
SUM(OCTUBRE[PREUNIVERSITARIOS // SI ESAM: PAQUETES MENSUAL CONTADO (S2)]) +
SUM(OCTUBRE[PREUNIVERSITARIOS // SI ESAM: PAQUETES MENSUAL CONTADO (S3)]) +
SUM(OCTUBRE[PREUNIVERSITARIOS // SI ESAM: PAQUETES MENSUAL CONTADO (S4)])

PREUNIVERSITARIOS / SI ESAM CREDITO - OCT = 
SUM(OCTUBRE[PREUNIVERSITARIOS // SI ESAM: PAQUETES MENSUAL CREDITO (S1)]) +
SUM(OCTUBRE[PREUNIVERSITARIOS // SI ESAM: PAQUETES MENSUAL CREDITO (S2)]) +
SUM(OCTUBRE[PREUNIVERSITARIOS // SI ESAM: PAQUETES MENSUAL CREDITO (S3)]) +
SUM(OCTUBRE[PREUNIVERSITARIOS // SI ESAM: PAQUETES MENSUAL CREDITO (S4)])

DIPLOMADOS TECNICOS ISPI DE 4 MESES ANTICIPO - OCT = 
SUM(OCTUBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES ANTICIPO (S1)]) +
SUM(OCTUBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES ANTICIPO (S2)]) +
SUM(OCTUBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES ANTICIPO (S3)]) +
SUM(OCTUBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES ANTICIPO (S4)])

DIPLOMADOS TECNICOS ISPI DE 4 MESES CONTADO - OCT = 
SUM(OCTUBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES CONTADO (S1)]) +
SUM(OCTUBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES CONTADO (S2)]) +
SUM(OCTUBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES CONTADO (S3)]) +
SUM(OCTUBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES CONTADO (S4)])

DIPLOMADOS TECNICOS ISPI DE 4 MESES CREDITO - OCT = 
SUM(OCTUBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES CREDITO (S1)]) +
SUM(OCTUBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES CREDITO (S2)]) +
SUM(OCTUBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES CREDITO (S3)]) +
SUM(OCTUBRE[DIPLOMADOS TECNICOS ISPI DE 4 MESES CREDITO (S4)])

DIPLOMADOS TECNICOS UPI DE 4 MESES / FORMACION CONTINUA UPI ANTICIPO - OCT = 
SUM(OCTUBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) ANTICIPO (S1)]) +
SUM(OCTUBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) ANTICIPO (S2)]) +
SUM(OCTUBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) ANTICIPO (S1)]) +
SUM(OCTUBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) ANTICIPO (S1)])

DIPLOMADOS TECNICOS UPI DE 4 MESES / FORMACION CONTINUA UPI CONTADO - OCT = 
SUM(OCTUBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) CONTADO (S1)]) +
SUM(OCTUBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) CONTADO (S2)]) +
SUM(OCTUBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) CONTADO (S3)]) +
SUM(OCTUBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) CONTADO (S4)])

DIPLOMADOS TECNICOS UPI DE 4 MESES / FORMACION CONTINUA UPI CREDITO - OCT = 
SUM(OCTUBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) CREDITO (S1)]) +
SUM(OCTUBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) CREDITO (S2)]) +
SUM(OCTUBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) CREDITO (S3)]) +
SUM(OCTUBRE[DIPLOMADOS TECNICOS UPI DE 5 MESES // FORMACION CONTINUA UPI (BOLIVIA) CREDITO (S4)])

CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) / NIDITO ANTICIPO - OCT = 
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI ANTICIPO (S1)]) +
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI ANTICIPO (S2)]) +
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI ANTICIPO (S3)]) +
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI ANTICIPO (S4)])

CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) / NIDITO CONTADO - OCT = 
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI CONTADO (S1)]) +
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI CONTADO (S2)]) +
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI CONTADO (S3)]) +
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI CONTADO (S4)])

CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) / NIDITO CREDITO - OCT = 
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI CREDITO (S1)]) +
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI CREDITO (S2)]) +
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI CREDITO (S3)]) +
SUM(OCTUBRE[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) // NIDITO // SI ESAM: PAQUETE ANUAL // CARRERAS UPI CREDITO (S4)])

CARRERAS - LICENCIATURAS / KINDER 1RA - 2DA SECCION / ALUMNOS PRIMARIA - SECUNDARIA / DIPLOMADOS UPI ANTICIPO - OCT = 
SUM(OCTUBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) ANTICIPO (S1)]) +
SUM(OCTUBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) ANTICIPO (S2)]) +
SUM(OCTUBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) ANTICIPO (S3)]) +
SUM(OCTUBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) ANTICIPO (S4)])

CARRERAS - LICENCIATURAS / KINDER 1RA - 2DA SECCION / ALUMNOS PRIMARIA - SECUNDARIA / DIPLOMADOS UPI CONTADO - OCT = 
SUM(OCTUBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) CONTADO (S1)]) +
SUM(OCTUBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) CONTADO (S2)]) +
SUM(OCTUBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) CONTADO (S3)]) +
SUM(OCTUBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) CONTADO (S4)])

CARRERAS - LICENCIATURAS / KINDER 1RA - 2DA SECCION / ALUMNOS PRIMARIA - SECUNDARIA / DIPLOMADOS UPI CREDITO - OCT = 
SUM(OCTUBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) CREDITO (S1)]) +
SUM(OCTUBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) CREDITO (S2)]) +
SUM(OCTUBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) CREDITO (S3)]) +
SUM(OCTUBRE[CARRERAS CCA // KINDER 1RA - 2DA SECCION // ALUMNOS PRIMARIA - SECUNDARIA // DIPLOMADOS UPI PG (PANAMA) CREDITO (S4)])

PREINICIAL / ESPECIALIDADES POSGRADO ANTICIPO - OCT = 
SUM(OCTUBRE[PREINICIAL // ESPECIALIDADES ANTICIPO (S1)]) +
SUM(OCTUBRE[PREINICIAL // ESPECIALIDADES ANTICIPO (S2)]) +
SUM(OCTUBRE[PREINICIAL // ESPECIALIDADES ANTICIPO (S3)]) +
SUM(OCTUBRE[PREINICIAL // ESPECIALIDADES ANTICIPO (S4)])

PREINICIAL / ESPECIALIDADES POSGRADO CONTADO - OCT = 
SUM(OCTUBRE[PREINICIAL // ESPECIALIDADES CONTADO (S1)]) +
SUM(OCTUBRE[PREINICIAL // ESPECIALIDADES CONTADO (S2)]) +
SUM(OCTUBRE[PREINICIAL // ESPECIALIDADES CONTADO (S3)]) +
SUM(OCTUBRE[PREINICIAL // ESPECIALIDADES CONTADO (S4)])

PREINICIAL / ESPECIALIDADES POSGRADO CREDITO - OCT = 
SUM(OCTUBRE[PREINICIAL // ESPECIALIDADES CREDITO (S1)]) +
SUM(OCTUBRE[PREINICIAL // ESPECIALIDADES CREDITO (S2)]) +
SUM(OCTUBRE[PREINICIAL // ESPECIALIDADES CREDITO (S3)]) +
SUM(OCTUBRE[PREINICIAL // ESPECIALIDADES CREDITO (S4)])

DIPLOMADOS POSGRADO ANTICIPO - OCT = 
SUM(OCTUBRE[DIPLOMADOS ANTICIPO (S1)]) +
SUM(OCTUBRE[DIPLOMADOS ANTICIPO (S2)]) +
SUM(OCTUBRE[DIPLOMADOS ANTICIPO (S3)]) +
SUM(OCTUBRE[DIPLOMADOS ANTICIPO (S4)])

DIPLOMADOS POSGRADO CONTADO - OCT = 
SUM(OCTUBRE[DIPLOMADOS CONTADO (S1)]) +
SUM(OCTUBRE[DIPLOMADOS CONTADO (S2)]) +
SUM(OCTUBRE[DIPLOMADOS CONTADO (S3)]) +
SUM(OCTUBRE[DIPLOMADOS CONTADO (S4)])

DIPLOMADOS POSGRADO CREDITO - OCT = 
SUM(OCTUBRE[DIPLOMADOS CREDITO (S1)]) +
SUM(OCTUBRE[DIPLOMADOS CREDITO (S2)]) +
SUM(OCTUBRE[DIPLOMADOS CREDITO (S3)]) +
SUM(OCTUBRE[DIPLOMADOS CREDITO (S4)])

DIPLOMADOS POSGRADO UABJB CONTADO - OCT = 
SUM(OCTUBRE[DIPLOMADOS CONTADO UABJB (S1)]) +
SUM(OCTUBRE[DIPLOMADOS CONTADO UABJB (S2)]) +
SUM(OCTUBRE[DIPLOMADOS CONTADO UABJB (S3)]) +
SUM(OCTUBRE[DIPLOMADOS CONTADO UABJB (S4)])

DIPLOMADOS POSGRADO UABJB CREDITO - OCT = 
SUM(OCTUBRE[DIPLOMADOS CREDITO UABJB (S1)]) +
SUM(OCTUBRE[DIPLOMADOS CREDITO UABJB (S2)]) +
SUM(OCTUBRE[DIPLOMADOS CREDITO UABJB (S3)]) +
SUM(OCTUBRE[DIPLOMADOS CREDITO UABJB (S4)])

MAESTRIAS POSGRADO ANTICIPO - OCT = 
SUM(OCTUBRE[MAESTRIAS ANTICIPO (S1)]) +
SUM(OCTUBRE[MAESTRIAS ANTICIPO (S2)]) +
SUM(OCTUBRE[MAESTRIAS ANTICIPO (S3)]) +
SUM(OCTUBRE[MAESTRIAS ANTICIPO (S4)])

MAESTRIAS POSGRADO CONTADO - OCT = 
SUM(OCTUBRE[MAESTRIAS CONTADO (S1)]) +
SUM(OCTUBRE[MAESTRIAS CONTADO (S2)]) +
SUM(OCTUBRE[MAESTRIAS CONTADO (S3)]) +
SUM(OCTUBRE[MAESTRIAS CONTADO (S4)])

MAESTRIAS POSGRADO CREDITO - OCT = 
SUM(OCTUBRE[MAESTRIAS CREDITO (S1)]) +
SUM(OCTUBRE[MAESTRIAS CREDITO (S2)]) +
SUM(OCTUBRE[MAESTRIAS CREDITO (S3)]) +
SUM(OCTUBRE[MAESTRIAS CREDITO (S4)])

MAESTRIAS POSGRADO UABJB CONTADO - OCT = 
SUM(OCTUBRE[MAESTRIAS CONTADO UABJB (S1)]) +
SUM(OCTUBRE[MAESTRIAS CONTADO UABJB (S2)]) +
SUM(OCTUBRE[MAESTRIAS CONTADO UABJB (S3)]) +
SUM(OCTUBRE[MAESTRIAS CONTADO UABJB (S4)])

MAESTRIAS POSGRADO UABJB CREDITO - OCT = 
SUM(OCTUBRE[MAESTRIAS CREDITO UABJB (S1)]) +
SUM(OCTUBRE[MAESTRIAS CREDITO UABJB (S2)]) +
SUM(OCTUBRE[MAESTRIAS CREDITO UABJB (S3)]) +
SUM(OCTUBRE[MAESTRIAS CREDITO UABJB (S4)])

/* TOTALES */

TOTAL CAPACITACIÓN CA - OCT = 
[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CONTADO - OCT] +
[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CREDITO - OCT]

TOTAL CAPACITACIÓN LA / NIDITO / CARRERAS UPI - OCT = 
[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) / NIDITO CONTADO - OCT] +
[CURSOS DE CAPACITACIÓN (DE 5 MESES HASTA 1 AÑO) / NIDITO CREDITO - OCT]

TOTAL CARRERAS / KINDER / ALUMNOS / UPI PG - OCT = 
[CARRERAS - LICENCIATURAS / KINDER 1RA - 2DA SECCION / ALUMNOS PRIMARIA - SECUNDARIA / DIPLOMADOS UPI CONTADO - OCT] +
[CARRERAS - LICENCIATURAS / KINDER 1RA - 2DA SECCION / ALUMNOS PRIMARIA - SECUNDARIA / DIPLOMADOS UPI CREDITO - OCT]

TOTAL ESPECIALIDADES POSGRADO - OCT = 
[PREINICIAL / ESPECIALIDADES POSGRADO ANTICIPO - OCT] + 
[PREINICIAL / ESPECIALIDADES POSGRADO CREDITO - OCT]

TOTAL DIPLOMADOS POSGRADO - OCT = 
[DIPLOMADOS POSGRADO CONTADO - OCT] + 
[DIPLOMADOS POSGRADO CREDITO - OCT] +
[DIPLOMADOS POSGRADO UABJB CONTADO - OCT] +
[DIPLOMADOS POSGRADO UABJB CREDITO - OCT]

TOTAL UPI FC - OCT = 
[DIPLOMADOS TECNICOS UPI DE 4 MESES / FORMACION CONTINUA UPI CONTADO - OCT] +
[DIPLOMADOS TECNICOS UPI DE 4 MESES / FORMACION CONTINUA UPI CREDITO - OCT]

TOTAL DIPLOMADOS - OCT = 
[TOTAL DIPLOMADOS POSGRADO - OCT] + 
[TOTAL CARRERAS / KINDER / ALUMNOS / UPI PG - OCT] +
[TOTAL UPI FC - OCT]

TOTAL MAESTRIAS POSGRADO - OCT = 
[MAESTRIAS POSGRADO CONTADO - OCT] + 
[MAESTRIAS POSGRADO CREDITO - OCT] +
[MAESTRIAS POSGRADO UABJB CONTADO - OCT] +
[MAESTRIAS POSGRADO UABJB CREDITO - OCT]

TOTAL POSGRADO - OCT = 
[TOTAL DIPLOMADOS POSGRADO - OCT] + 
[TOTAL ESPECIALIDADES POSGRADO - OCT] + 
[TOTAL MAESTRIAS POSGRADO - OCT]

TOTAL POSGRADO Y UPI FC - OCT = 
[TOTAL POSGRADO - OCT] +
[TOTAL UPI FC - OCT]

TOTAL CORTO ALCANCE - OCT = 
[CURSOS DE FORMACIÓN CONTINUA (DESDE 1 DÍA HASTA 2 MESES) - OCT] +
[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CONTADO - OCT] +
[CURSOS DE CAPACITACIÓN (DESDE 3 MESES HASTA LOS 5 MESES) CREDITO - OCT] +
[PREUNIVERSITARIOS / SI ESAM CONTADO - OCT] +
[PREUNIVERSITARIOS / SI ESAM CREDITO - OCT] +
[DIPLOMADOS TECNICOS ISPI DE 4 MESES CONTADO - OCT] +
[DIPLOMADOS TECNICOS ISPI DE 4 MESES CREDITO - OCT] +
[DIPLOMADOS TECNICOS UPI DE 4 MESES / FORMACION CONTINUA UPI CONTADO - OCT]+
[DIPLOMADOS TECNICOS UPI DE 4 MESES / FORMACION CONTINUA UPI CREDITO - OCT]

TOTAL LARGO ALCANCE - OCT = 
SUM(OCTUBRE[SUBTOTAL LARGO ALCANCE COMPLETO (S1)]) +
SUM(OCTUBRE[SUBTOTAL LARGO ALCANCE COMPLETO (S2)]) +
SUM(OCTUBRE[SUBTOTAL LARGO ALCANCE COMPLETO (S3)]) +
SUM(OCTUBRE[SUBTOTAL LARGO ALCANCE COMPLETO (S4)])

TOTAL LARGO ALCANCE CONTADO - OCT = 
SUM(OCTUBRE[SUBTOTAL LARGO ALCANCE - PLAN AL CONTADO COMPLETO (S1)]) +
SUM(OCTUBRE[SUBTOTAL LARGO ALCANCE - PLAN AL CONTADO COMPLETO (S2)]) +
SUM(OCTUBRE[SUBTOTAL LARGO ALCANCE - PLAN AL CONTADO COMPLETO (S3)]) +
SUM(OCTUBRE[SUBTOTAL LARGO ALCANCE - PLAN AL CONTADO COMPLETO (S4)])

TOTAL SEDE - OCT = 
SUM(OCTUBRE[TOTAL DE SEDE (S1)]) +
SUM(OCTUBRE[TOTAL DE SEDE (S2)]) +
SUM(OCTUBRE[TOTAL DE SEDE (S3)]) +
SUM(OCTUBRE[TOTAL DE SEDE (S4)])